-- Doctor details are: 
-- Doctor Name,
-- Education degrees,
-- Specialty e.g. ENT Surgeon,
-- Total Experience,
-- Consulting Time slots,
-- Consulting Charges


Use Pams_own;

Drop table if exists DOCTOR_RECORD;

CREATE TABLE DOCTOR_RECORD
(
DOCTOR_ID INT auto_increment primary key not null,
DOCTOR_NAME varchar(40),
TOTAL_EXPERIENCE INT,
CONSULTING_CHARGE INT,
EDUCATION_DEGREE VARCHAR (200),
SPECIALITY VARCHAR(255)
);

-- CONSULTING_TIME enum('9:30AM','10:00AM','10:30AM','11:00AM','11:30AM','12:00AM','12:30PM','13:00PM'),

INSERT INTO DOCTOR_RECORD(DOCTOR_NAME,TOTAL_EXPERIENCE,CONSULTING_CHARGE,EDUCATION_DEGREE,SPECIALITY)
VALUES('Shirish Deshpande', 12, 450, 'MBBS','GeneralPhysician');


INSERT INTO DOCTOR_RECORD (DOCTOR_NAME,TOTAL_EXPERIENCE,CONSULTING_CHARGE,EDUCATION_DEGREE,SPECIALITY) VALUES('DilipBhurte', 24, 600, 'MBBS, MD','orthipadic');
INSERT INTO DOCTOR_RECORD(DOCTOR_NAME,TOTAL_EXPERIENCE,CONSULTING_CHARGE,EDUCATION_DEGREE,SPECIALITY) VALUES('Shirishvalsangkar', 16, 500, 'MBBS MD','Neuro Surgon');
INSERT INTO DOCTOR_RECORD(DOCTOR_NAME,TOTAL_EXPERIENCE,CONSULTING_CHARGE,EDUCATION_DEGREE,SPECIALITY) VALUES("SaumyaAwasti", 5, 300, 'MBBS','Gynacologist');
INSERT INTO DOCTOR_RECORD(DOCTOR_NAME,TOTAL_EXPERIENCE,CONSULTING_CHARGE,EDUCATION_DEGREE,SPECIALITY) VALUES('VinayTripathi', 21, 700, 'MBBS, MD','Ortho Surgeon');
INSERT INTO DOCTOR_RECORD(DOCTOR_NAME,TOTAL_EXPERIENCE,CONSULTING_CHARGE,EDUCATION_DEGREE,SPECIALITY) VALUES('Niharkale', 12, 450,'MBBS','Psychiatrist');


select * from DOCTOR_RECORD;